### PR TITLE
Add default weight "classes"

### PR DESCRIPTION
**Pull request by jsbean**
This PR replaces magic numbers in initial `FlowNetwork` hook-up and in tests. Instead, boxing weight classes are used 👊.

This could get wrapped up into an `enum` for better namespacing.

### CODE REVIEW

**Comment by bwetherfield** [comment]
Can this go straight into master (as well as the additional tests)? Minimizing red-onto-red travis scenarios

**Comment by jsbean** [comment]
I could probably at least cherry pick 6ec7b82c17449607fe104ca122e7fbdb75eeec41.

**Comment by bwetherfield** [comment]
I do think maybe I can skim number comparisons faster than weight-class comparisons but opinions may differ on that!

**Comment by bwetherfield** [comment]
The magic numbers are definitely fairly arbitrary, so it makes sense to want to change em

**Comment by jsbean** [comment]
Yeah, I just want to avoid the point when we change what those magic numbers are on the source side, then all of a sudden the flownetwork construction tests fail and it will feel muddy.

But yeah, if you have another analogy, I'm all ears :).

**Comment by bwetherfield** [comment]
It's kind of too perfect seeing as we are dealing with "weights" anyway!

**Comment by bwetherfield** [comment]
tough to beat that

**Pull request merged**
