### PR TITLE
Remove tendency graph

### PR DESCRIPTION
**Pull request by bwetherfield**
Cuts down on intermediate `static` constants.

### CODE REVIEW

**Comment by bwetherfield** [comment]
Any idea what went wrong with Travis here, @jsbean ?

**Comment by jsbean** [comment]
Looks like it barfed when trying to upload the Swift toolchain for Linux. I restarted it. We shall see how that goes.

**Comment by jsbean** [comment]
All good!

**Comment by bwetherfield** [comment]
Seems to have worked!

**Pull request merged**
